pool: 
  name: $(agentName)

jobs:
- job: Migrate 
  timeoutInMinutes: 0
  steps:
    - task: AzureCLI@2
      displayName: Get Storage Migration Results
      inputs:
        azureSubscription: $(azureSubscriptionEndpoint)
        scriptType: 'ps'
        addSpnToEnvironment: true
        scriptLocation: 'scriptPath'
        scriptPath: './GetMigrationResult.ps1'
        arguments: -srcStorageAccountName $(srcStorageAccountName) -srcStorageAccessKey $(srcStorageAccessKey) -destinationStorageAccountName $(destinationStorageAccountName) -resultType $(resultType) -startIndex $(startIndex) -endIndex $(endIndex)